# -*- coding: utf-8 -*-
"""Group_9_Draft_.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lr7AARliuo0VB-2fnRXMQfv3PtKDcsr0

**CAPSTONE** **PROJECT**
"""

# Capstone Project - Pedestrian Road Casualties Analysis
## Group 9: Nicole Wainaina & Emmanuel Juma
### Feature Engineering + Full Analysis
#**Week 7 Focus**: Data Preparation, Cleaning & Feature Engineering

"""**Import Libraries**"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm
from statsmodels.formula.api import glm
from statsmodels.genmod.families import Binomial
from statsmodels.tsa.arima.model import ARIMA
from sklearn.preprocessing import LabelEncoder

sns.set_style("whitegrid")
print("✅ All libraries imported successfully!")

"""**Upload** **Dataset**"""

from google.colab import files
uploaded = files.upload()

# Load the data
df = pd.read_excel('knbs002-road-accident-casualties-qoabis.xlsx', sheet_name='Sheet1')

# Basic cleaning
df['OBS_VALUE'] = pd.to_numeric(df['OBS_VALUE'], errors='coerce')
df['TIME_PERIOD'] = pd.to_numeric(df['TIME_PERIOD'], errors='coerce')

print("Dataset loaded successfully!")
print("Shape:", df.shape)
print(df.head())

"""**Feature** **Engineering**"""

print("🔧 Starting Feature Engineering...")

# 1. Create Total Casualties per Year & Road User
df_grouped = df.groupby(['TIME_PERIOD', 'ROAD_USER', 'INJURY_TYPE'])['OBS_VALUE'].sum().reset_index()

# 2. Pivot to wide format for easier analysis
df_pivot = df_grouped.pivot_table(index=['TIME_PERIOD', 'ROAD_USER'],
                                  columns='INJURY_TYPE',
                                  values='OBS_VALUE',
                                  fill_value=0).reset_index()

# Rename columns for clarity
df_pivot = df_pivot.rename(columns={
    'Killed': 'KILLED',
    'Seriously Injured': 'SERIOUSLY_INJURED',
    'Slightly Injured': 'SLIGHTLY_INJURED'
})

# 3. Derived Features (Core Feature Engineering)
df_pivot['TOTAL_CASUALTIES'] = (df_pivot['KILLED'] +
                                df_pivot['SERIOUSLY_INJURED'] +
                                df_pivot['SLIGHTLY_INJURED'])

df_pivot['FATALITY_RATE'] = (df_pivot['KILLED'] / df_pivot['TOTAL_CASUALTIES'] * 100).round(2)

df_pivot['SERIOUS_INJURY_RATE'] = (df_pivot['SERIOUSLY_INJURED'] / df_pivot['TOTAL_CASUALTIES'] * 100).round(2)

# 4. Pedestrian-Specific Flags and Features
df_pivot['IS_PEDESTRIAN'] = (df_pivot['ROAD_USER'] == 'Pedestrians').astype(int)

# 5. Vulnerability Index (New engineered feature)
# Combines fatality rate and proportion of serious injuries
df_pivot['VULNERABILITY_INDEX'] = (df_pivot['FATALITY_RATE'] * 0.7 +
                                   df_pivot['SERIOUS_INJURY_RATE'] * 0.3).round(2)

# 6. Year as numeric for modeling
df_pivot['YEAR'] = df_pivot['TIME_PERIOD']

print("✅ Feature Engineering Completed!")
print("\nNew Engineered Features:")
print(df_pivot.columns.tolist())
print("\nSample of engineered data:")
print(df_pivot.head())

"""**Exploratory** **Data** **Analysis** (**EDA**) **after** **Feature** **Engineering**"""

# Pedestrian Share Analysis
total_casualties_year = df_pivot.groupby('YEAR')['TOTAL_CASUALTIES'].sum().reset_index()
pedestrian_data = df_pivot[df_pivot['ROAD_USER'] == 'Pedestrians']

ped_share = pd.merge(total_casualties_year,
                     pedestrian_data[['YEAR', 'TOTAL_CASUALTIES']],
                     on='YEAR', suffixes=('_total', '_ped'))

ped_share['PED_SHARE_%'] = (ped_share['TOTAL_CASUALTIES_ped'] / ped_share['TOTAL_CASUALTIES_total'] * 100).round(2)

# Visualisation
plt.figure(figsize=(10, 6))
sns.barplot(data=ped_share, x='YEAR', y='PED_SHARE_%', palette='Blues_d')
plt.title('Pedestrian Share of Total Road Casualties (%)')
plt.ylabel('Percentage (%)')
plt.show()

"""**Fatality** **Rate** **Visualisation**"""

# Fatality Rate by Road User
fatality_summary = df_pivot.groupby('ROAD_USER')['FATALITY_RATE'].mean().sort_values(ascending=False)

plt.figure(figsize=(12, 7))
fatality_summary.plot(kind='bar', color='skyblue')
plt.title('Average Fatality Rate by Road User (2018-2021)')
plt.ylabel('Fatality Rate (%)')
plt.xticks(rotation=45)
plt.show()

print(fatality_summary)

"""**Linear** **Regression** **on** **Pedestrian** **Casualties**"""

# Linear Regression for Trend
ped_data = pedestrian_data[['YEAR', 'TOTAL_CASUALTIES']].copy()
X = sm.add_constant(ped_data['YEAR'])
y = ped_data['TOTAL_CASUALTIES']

model = sm.OLS(y, X).fit()
print(model.summary())

# Plot Trend
plt.figure(figsize=(10, 6))
sns.regplot(x='YEAR', y='TOTAL_CASUALTIES', data=ped_data, ci=None)
plt.title('Trend in Pedestrian Total Casualties with Linear Regression')
plt.show()

"""**Binomial Logistic Regression**"""

# Prepare data for logistic regression (binomial)
df_model = df_pivot.copy()
df_model = pd.get_dummies(df_model, columns=['ROAD_USER'], drop_first=True, prefix='USER')

# Select features
X = df_model[['YEAR'] + [col for col in df_model.columns if col.startswith('USER_')]]
X = sm.add_constant(X)

# Convert all columns in X to numeric (float) to handle boolean dummy variables
X = X.astype(float)

# Endog for binomial: successes (killed) and failures (survived)
endog = np.column_stack((df_model['KILLED'], df_model['TOTAL_CASUALTIES'] - df_model['KILLED']))

logit_model = sm.GLM(endog, X, family=Binomial()).fit()
print(logit_model.summary())

"""**Arima Forecasting**"""

# ARIMA on Pedestrian Killed
ped_killed = df[(df['ROAD_USER'] == 'Pedestrians') & (df['INJURY_TYPE'] == 'Killed')]
ped_killed_ts = ped_killed.groupby('TIME_PERIOD')['OBS_VALUE'].sum()

arima_model = ARIMA(ped_killed_ts, order=(1, 1, 0))
arima_fit = arima_model.fit()
forecast = arima_fit.forecast(steps=2)

print("🚀 ARIMA Forecast for Pedestrian Killed:")
print("2022:", round(forecast.iloc[0], 0))
print("2023:", round(forecast.iloc[1], 0))

# Save the engineered dataset for future use
df_pivot.to_excel('engineered_road_casualties.xlsx', index=False)
files.download('engineered_road_casualties.xlsx')
print("✅ Engineered dataset downloaded!")